version: "3.7"

services:
  ml-api:
    image: ml_api:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile_api
    depends_on:
      - broker
      - zookeeper
    ports:
      - 8000:8000
    volumes:
      - ../src/:/app/
    tty: true
    working_dir: /app/ml_api/
    #command: bash
    command: python3 cli/manage.py start-reload
